name: bugsnag_bridge
description: "BugSnag flutter bridge."
version: 2.0.0
homepage: https://www.bugsnag.com/
repository: https://github.com/bugsnag/bugsnag-flutter-common
issue_tracker: https://github.com/bugsnag/bugsnag-flutter-common/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
