name: bugsnag_http_client
description: "BugSnag flutter http client wrapper."
version: 2.1.0
homepage: https://www.bugsnag.com/
documentation: https://docs.bugsnag.com/performance/flutter/
repository: https://github.com/bugsnag/bugsnag-flutter-common
issue_tracker: https://github.com/bugsnag/bugsnag-flutter-common/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  bugsnag_bridge:
    path: ../bugsnag_bridge

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
